CREATE TABLE USER(
    USER_ID VARCHAR(20),
    USER_PW VARCHAR(512),
    SALT VARCHAR(512),
    NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(30),
    TOKEN VARCHAR(255),
    PRIMARY KEY(USER_ID)
);