use autoinmall;

drop table USER;
drop table ITEM;
drop table CART;
drop table CATEGORY;
drop table MODEL;
drop table MANUFACTURER;

CREATE TABLE USER(
    USER_ID VARCHAR(20),
    USER_PW VARCHAR(512),
    SALT VARCHAR(512),
    NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(30),
    ADDRESS VARCHAR(50),
    ZIPCODE VARCHAR(20),
    TOKEN INT(1),
    PRIMARY KEY(USER_ID)
);

CREATE TABLE ITEM(
    ITEM_NAME VARCHAR(30),
    PIN VARCHAR(256),
    PARTS_NUM VARCHAR(30),
    VOLUME INT(20),
    PRICE FLOAT(20),
    ITEM_DESC VARCHAR(500),
    RATE INT(5),
    PRIMARY KEY(PIN)   
);

CREATE TABLE CART(
    ID VARCHAR(20),
    ITEM VARCHAR(50),
    PRICE FLOAT(20),
    PIN VARCHAR(256),
    VOLUME INT(20),
    PARTS_NUM VARCHAR(30),
    PRIMARY KEY (PIN),
    FOREIGN KEY (ID) REFERENCES USER (USER_ID)    
);

CREATE TABLE RECEIPT(
    RECIPIENT VARCHAR(50),
    ORDER_NUM INT(50),
    PIN VARCHAR(100),
    ADDRESS VARCHAR(50),
    ZIPCODE VARCHAR(20),
    TOTAL FLOAT(50),
    PRIMARY KEY (ORDER_NUM),
    FOREIGN KEY (RECIPIENT) REFERENCES USER (USER_ID)
);

CREATE TABLE ITEMINFO(
    MAIN_C VARCHAR(30),
    SUB_C VARCHAR(30),
    BASE_M VARCHAR(30),
    DETAIL_M VARCHAR(50),
    CAR_M VARCHAR(30),
    ITEM_M VARCHAR(30),
    ITEM_NUM VARCHAR(256),
    PRIMARY KEY (ITEM_NUM),
    FOREIGN KEY (ITEM_NUM) REFERENCES ITEM (PIN)
);

